name: sysnet

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cargo build
      run: cargo build --verbose

    - name: Cargo run
      run: cargo run -- -a

    - name: Cargo run
      run: cargo run -- -p
